# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mark Schaal
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markschaal.com" # the base hostname & protocol for your site
twitter_username: mschaal
github_username:  mark-schaal

# Author information
author: Mark Schaal
author_position: Technical Lead / Senior Developer
author_bio: > # Lorem ipsum dolor sit amet nunca sit si quillabet.
email: markschaal@gmail.com

# Pagination settings
paginate: 2
paginate_path: "/blog/page:num/"
excerpt_separator: <!--more-->

# Build settings
markdown: kramdown

# Additional Gem functionalities
gems: jekyll-paginate

# SASS settings
sass:
  sass_dir: _sass
  style: compressed
